# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: salmanso <salmanso@student.42abudhabi.ae>  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/03/24 20:19:30 by salmanso          #+#    #+#              #
#    Updated: 2023/03/25 14:43:36 by salmanso         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	=	fractol
CC		=	cc
CFLAGS	=	-Wall -Werror -Wextra
SRC		=	*.c

OBJ		=	$(SRC:.c=.o)

all		:	$(NAME)

$(NAME)	:

$(OBJ)	:
